### ISSUE TITLE
 Error in clusterCells(): Could not find function "jaccard_coeff"

### ISSUE THREAD

**Issue by qrzhang** [cole-trapnell-lab/monocle-release#100]
Happy New Year!

Q1. I got an error message while running clusterCells() under monocle 2.6.1.
`> AGG_loop <- clusterCells(AGG_loop,  method = "louvain", verbose = T)`
`Run phenograph starts:`
  `-Input data of 22851 rows and 2 columns`
 ` -k is set to 50`
 ` Finding nearest neighbors...DONE ~ 0.223 s`
  `Compute jaccard coefficient between nearest-neighbor sets...Error in jaccard_coeff(neighborMatrix, weight) : `
  `could not find function "jaccard_coeff"`
I could not find any related solution anywhere. 

Q2,  I used default method "densityPeak" in clusterCells() before, but the results (attached below) confused me a lot as cells in A(the dark red circle) and B (the Black circle) are close to each other but clustered to different groups with further cells. That is why I want to use the new method "louvain" now. Hence, I will appreciate if you could give me any suggestion on better clustering cells. Thank you.
￼
![artboard](https://user-images.githubusercontent.com/19705471/34617813-90a111f0-f277-11e7-9568-09be1892f2cc.png)

￼

**Comment by Xiaojieqiu** [comment]
Happy New Year. For your first question, we confronted this error before and I believe it is fixed and validated in our lab but for some reason it didn't update on github release version or bioconductor. The error relates to exporting c++ based code in R. For now, you can apply `load_all` function while the `pkg` argument points to the local directory of the git cloned monocle repo from `devtools` package to ensure this function is accessible. I will get this sorted out once I have more free time. For your second question, I believe you may need to look at the decision plot (use the `plot_rho_delta` function) to manually select a good set of `rho, delta` value and pass them to the clusterCell function. I think the A, B groups can be regarded as a new cluster. The reason we have this result probably because those cells belong to the cluster halos or noise points at the boundary of two clusters and could have ambiguous clustering results, etc. (see the original Science paper of density peak for more details if you are interested). We may show the cluster halos in future
