### ISSUE TITLE
clusterCells throws error if max_components < length(clustering_genes)

### ISSUE THREAD

**Issue by hnakhoul** [cole-trapnell-lab/monocle-release#11]
Looks like it's coming from the call to kmeans in reduceDimension(). Might be better to reset max_components if few clustering genes are specified, or at least to stop with a more informative error message.

**Comment by Xiaojieqiu** [comment]
You mean `max_components > length(clustering_genes)`, right? 

Currently Monocle 2 replaces its previous clustering approach based on DDRTree with a new strategy based on density peak clustering which can handle tens of thousands or potentially millions of cells efficiently. 

I think this issue is resolved and will close it now.
