### ISSUE TITLE
OrderCells failing when tsne used for dimension reduction

### ISSUE THREAD

**Issue by MattMyint** [cole-trapnell-lab/monocle-release#113]
Hi,

I was using monocle and noticed that for dimension reduction, the default DDRTree works great, but there's also the option to use tsne.

When using DDRTree for dimension reduction, the orderCells function works fine. However, when I do 
`reduceDimension(data, max_components=2, reduction_method = "tSNE", norm_method = "none")`
I get the following messages:

```
> data <- reduceDimension(data, max_components=2, reduction_method = "tSNE", norm_method = "none")
Warning in (function (A, nv = 5, nu = nv, maxit = 1000, work = nv + 7, reorth = TRUE,  :
  You're computing too large a percentage of total singular values, use a standard svd instead.
Warning in (function (A, nv = 5, nu = nv, maxit = 1000, work = nv + 7, reorth = TRUE,  :
  did not converge--results might be invalid!; try increasing work or maxit
> data <- orderCells(data, reverse=FALSE)
Error in orderCells(data, reverse = FALSE) : 
  Error: dimension reduction didn't prodvide correct results. Please check your reduceDimension() step and ensure correct dimension reduction are performed before calling this function.
```

I looked into the code for OrderCells and found these lines (1075-1078 of ordercells.R)

```
# reducedDimA, S, and K are not NULL in the cds
  if (any(c(length(cds@reducedDimS) == 0, length(cds@reducedDimK) == 0))) {
    stop("Error: dimension reduction didn't prodvide correct results. Please check your reduceDimension() step and ensure correct dimension reduction are performed before calling this function.")
  }
```

I observed that the tsne results are stored in reducedDimA, but these lines suggest that it doesn't see them and stops the function. Is there something missing from the steps i took?

**Comment by Xiaojieqiu** [comment]
Hi Matt, we don't suggest you use tSNE for trajectory inference. The reason is obvious because tSNE is great at getting the clustering structure but not for trajectory inference as the global distance on tSNE map (i.e distance between two clusters)  doesn't  have much meaning (close clusters are not necessarily close cell types, etc.) theoretically. also, we are working on new updates of Monocle which will provide more state-of-the-art algorithms for dimension reduction, so stay tuned if you are interested in trying other dimension reductions for trajectory inference.

**Comment by MattMyint** [comment]
Okay, thank you! I've been using the DDR tree and its given good results with the data, so I'll stick with that. :)
