### ISSUE TITLE
best practice in extracting trajectories for brunched events.

### ISSUE THREAD

**Issue by LuyiTian** [cole-trapnell-lab/monocle-release#126]
imagining I have progenitor cells and differentiate into two types of mature cells (A and B) and have a `Y` shaped trajectory plot, now I want to find cells belong to each trajectory (progenitor cell -> A /  progenitor cell->B). What I found and seems to be useful is function `buildBranchCellDataSet`. Since these two trajectories share the same path before their fate split, the  `buildBranchCellDataSet` function seems to just randomly split these cells into each trajectory, but actually, you cant tell at that stage which mature cell type they will differentiate into. Is it just how the algorithm is designed for, or there are other considerations?

**Comment by Xiaojieqiu** [comment]
this was actually a discussion between the reviewers of Monocle 2 paper and us. We sequentially split cells into each branch because this approach enables us to perform BEAM test for the entire dataset while conforming the i.i.d (independent identically distributed) assumption required for the differential gene expression test. But I agree with you that we don't know which cell will belong to which lineage in the end. In fact `buildBranchCellDataSet` function (as well as `BEAM`) also supports duplicating the progenitor cells by setting `progenitor_method = TRUE`. This method gives similiar result with the other approach although at the risk of disobeying the statistical I.I.D. assumption
