### ISSUE TITLE
 object 'disp_table' not found when estimateDispersions(cds)

### ISSUE THREAD

**Issue by ShanSabri** [cole-trapnell-lab/monocle-release#16]
I am taking the averages of clusters of cells and running monocle with them. 

```
cluster.gene.avg.list = list()
for(n in unique(km$km.cluster)){
  cluster = scaled.data[, km$km.cluster %in% n]; 
  cluster.gene.avg.list[[n]] <- rowMeans(cluster)
}
cluster.avg = do.call(cbind, cluster.gene.avg.list)
colnames(cluster.avg) = paste0("C", colnames(cluster.avg))

```
`cluster.avg` looks something like this:
```
> head(cluster.avg[,1:5])
                 C16          C14          C3         C40          C4
A4GALT   -0.15852378 -0.268434779 -0.07329452  0.05332599 -0.05781838
AA413626 -0.06237282  0.007022857 -0.06237282 -0.06237282  0.03301530
AA414768  0.12676744 -0.054279647 -0.13331964 -0.05369653 -0.12118771
AA465934 -0.13563968 -0.209988851 -0.31531591 -0.24636586  0.08446100
AA987161 -0.13853327 -0.209409869  0.04191605 -0.22809665 -0.02878748
AAAS     -0.11055740 -0.167985646 -0.14395537 -0.16066358 -0.03010135
```

Looks okay but then... 

```

library(monocle)
pheno <- data.frame(row.names=colnames(cluster.avg), Cluster=colnames(cluster.avg))
cds <- newCellDataSet(as.matrix(cluster.avg),
                      phenoData=new("AnnotatedDataFrame", data=pheno), 
                      featureData=new("AnnotatedDataFrame", data=gene.design))
cds <- estimateSizeFactors(cds)
cds <- estimateDispersions(cds)
```
 returns the error: 

```
Error in estimateDispersionsForCellDataSet(object, modelFormulaStr, relative_expr,  : 
  object 'disp_table' not found
```

If I add `expressionFamily=negbinomial()` to `newCellDataSet` then the error changes to: 

```
Error in `[.data.frame`(`*tmp*`, res$mu == 0) : 
  undefined columns selected
```

Any help would be much appreciated. 

EDIT: I should mention that `gene.design` is a data.frame with gene information:

```
               Mean Disperson.Raw Disperson.Norm Pct.Cells.Exp
A4GALT   0.19691749      1.345950      0.3952008         0.052
AA413626 0.01126692      1.287438      0.1910357         0.003
AA414768 0.32179354      1.525643      0.6702481         0.084
AA465934 0.20542904      1.040429     -0.6708513         0.058
AA987161 0.25788802      1.354202      0.4239956         0.070
AAAS     0.35056009      1.154092     -0.7676060         0.105
```

**Comment by ctrapnell** [comment]
This is not actually a valid sequence of operations - estimateDispersions only works (and indeed is only needed) when you're using CellDataSet with a negbinomial or negbinomial.size expression family. If you're feeding Monocle cluster averages (really anything that's not transcript, UMI, or read count data) estimateDispersions will throw an error. We clearly need to throw more informative error messages.  Note however, that many downstream operations should still work.

The real fix here is to validate the CDS so that estimateDispersions emits a useful message rather than throwing an error. Likewise, operations that rely on count dispersions estimates should return warnings when the expression family is not negbinomial.

**Comment by brianpenghe** [comment]
Yes I noticed that estimateDispersions(cds) doesn't work for tobit (log-normal) expression family. Thanks

**Comment by Xiaojieqiu** [comment]
this has been fixed. now we print error message as follwoing: 

`estimateDispersions only works, and is only needed, when you're using a CellDataSet with a negbinomial or negbinomial.size expression family`
