### ISSUE TITLE
When importing log-transformed, normalized Seurat object, should i again log-transform  and normalize or not? 

### ISSUE THREAD

**Issue by kysbbubbu** [cole-trapnell-lab/monocle-release#162]
I want to initailly manage the data with Seurat and import it to monocle and do pseudotime constructio.

When importing log-transformed, normalized Seurat object, 

should i again log-transform  and normalize the imported CDS data or not? 

Thanks

**Comment by kysbbubbu** [comment]
@Xiaojieqiu Thanks for  answer 
Then, i might think that importing seurat data is not appropriate.
I will visualize clustering and biological interpretation by Seurat.
Later, do the pseudotime reconstruction to show developmental trajectory by Monocle.
It could be be the best way.

**Comment by jgarces02** [comment]
Hi @Xiaojieqiu, 

I've tried you said and it was impossible for my data... I have a data.frame from Seurat (obtained through **CCA** from two different tissues to compare) whose tSNE seems to behavior correctly deleting all batch effect:

![image](https://user-images.githubusercontent.com/27858969/45230936-c438e100-b2ca-11e8-9328-88983d5ed3dc.png)

With this data I've tried to create a monocle object with either seurat@scale.data or seurat@data but in both cases tSNE was totally different and batch effect was horrible!

![image](https://user-images.githubusercontent.com/27858969/45231234-ab7cfb00-b2cb-11e8-9490-a69b855af69b.png)

Any idea about what I'm doing incorrect, please? Thanks in advance!

**Comment by marong0511** [comment]
I have the same issue! @jgarces02

**Comment by skyyuntian** [comment]
@kysbbubbu I also have the same issue and similarly, I also want to do dimension reduction in seurat and do peudotime trajectory in monocle, but I don't quite understand the specific steps in this operation. Would you mind giving me some specific instructions?

**Comment by alextamburino** [comment]
@Xiaojieqiu Thanks for your time and answers.

I am interested in this topic and clearly so are others. Can you please address the concerns of @jgarces02 @skyyuntian and @marong0511 ?
I would like to make sure I'm applying and interpretting the tool correctly.

Thanks, Alex

**Comment by bishwaG** [comment]
> Hi @Xiaojieqiu,
> 
> I've tried you said and it was impossible for my data... I have a data.frame from Seurat (obtained through **CCA** from two different tissues to compare) whose tSNE seems to behavior correctly deleting all batch effect:
> 
> ![image](https://user-images.githubusercontent.com/27858969/45230936-c438e100-b2ca-11e8-9328-88983d5ed3dc.png)
> 
> With this data I've tried to create a monocle object with either [seurat@scale.data](mailto:seurat@scale.data) or seurat@data but in both cases tSNE was totally different and batch effect was horrible!
> 
> ![image](https://user-images.githubusercontent.com/27858969/45231234-ab7cfb00-b2cb-11e8-9490-a69b855af69b.png)
> 
> Any idea about what I'm doing incorrect, please? Thanks in advance!

@jgarces02 If you are using Seurat CCA, neither seurat@data not seurat@scale.data contains batch adjusted data.

**Comment by jgarces02** [comment]
Thanks @bishwaG, so is there any way to apply CCA correction over expression data to get a corrected matrix?

**Comment by alextamburino** [comment]
Thanks @bishwaG, that make perfect sense

**Comment by bishwaG** [comment]
I have not yet managed to do pseudotime analysis for my data that has undergone Seurat's CCA analysis pipeline. However, Seurat people said that they will add a feature which will enable us to extract batch corrected expression matrix. Please check issue [#948](https://github.com/satijalab/seurat/issues/948). I am impatiently waiting for that feature.

**Comment by liyini0823** [comment]
@Xiaojieqiu  I still want to ask the question :  if the result is correctly when I use Seurat to visualize clustering and biological interpretation, later, plot the developmental trajectory by monocle. 

But I find that use monocle importCDS() which import Seurat raw data and the result for Cells cluster are different between monocle2 and seurat.

How to solve this questions?
Thank you!

**Comment by LeiLi-Uchicago** [comment]
I have the same issue with @skyyuntian @jgarces02 @marong0511 
Thanks so much for all you guys' suggestions!
I figured out a way to make monocle V3 use Seurat V2 batch corrected data, but the way looks like cheating. Hope you guys can give me some comments.

I am using Seurat V2 and monocle V3. I try to find the corrected expression matrix from Seurat V2 but I failed, because as @bishwaG said, Seurat don't store a "corrected expression matrix". In my opinion, the "corrected expression matrix" in Seurat V2 is the aligned CCA matrix (like PCA we used before UMAP/t-SNE). Since monocle V3 ask for a gene expression matrix as input, it's impossible (and also does not make any sense) to use CCA matrix as input in monocle V3. 
I noticed that, same as Seurat V2, monocle V3 also perform PCA before UMAP/t-SNE reduction. If we replace the PCA matrix in  monocle V3 by aligned CCA matrix in Seurat V2, the problem seems to be solved. 
The PCA results in monocle V3 is `cds@normalized_data_projection`, the aligned CCA in Seurat V2 is `immune.combined@dr[["cca.aligned"]]@cell.embeddings`. Here `cds` is my monocle object and 
`immune.combined` is my Seurat object. I use `importCDS` to import `immune.combined` to `cds`. 

After we finish the pre-process:

> cds <- preprocessCDS(cds, num_dim = 20)

We can:

> cds@normalized_data_projection <- immune.combined@dr[["cca.aligned"]]@cell.embeddings
> cds <- reduceDimension(cds, reduction_method = 'UMAP')
> cds <- partitionCells(cds)
> cds <- learnGraph(cds,  RGE_method = 'SimplePPT')

Then we can check the results: 
> plot_cell_trajectory(cds, color_by = "cell_type")  + scale_color_manual(values = cell_type_color)

The UMAP visualization looks the same as my Seurat UMAP. 

Hope my poor English didn't confuse you guys, I am not a native speaker...
