### ISSUE TITLE
CellDataSet crashing Rstudio 1.0.136

### ISSUE THREAD

**Issue by HawkinsDakota** [cole-trapnell-lab/monocle-release#17]
I am currently trying to use Monocle for some new scRNAseq analysis. After executing newCellDataSet() RStudio aborts the current session. I am currently working with a relatively small dataset of filtered genes (24 genes by 48 samples), so file size is unlikely an issue. Creating a CellDataSet via command line R works fine, however, saving the object as an .rda file and loading the object in R once again forces a crash. I've replicated this error both on my Linux Mint desktop and my Macbook. 

I'm also able to replicate the crashing using a small, fake dataset: 

```{r}
library(monocle)
expr_test <- data.frame(S1 = c(1,1), S2 = c(0,0), row.names = c("G1", "G2"))
p_data <- data.frame(Group = c(1, 2), row.names = colnames(expr_test))
f_data <- data.frame(Anno = c("Foo", "Bar"), row.names = row.names(expr_test))
cell_data <- newCellDataSet(as.matrix(expr_test),
                            phenoData = new("AnnotatedDataFrame", data = p_data),
                            featureData = new("AnnotatedDataFrame", data = f_data))
```

Here is my session info with Monocle as the only specific library call:
```
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8      
 [2] LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8      
 [8] LC_NAME=C                 
 [9] LC_ADDRESS=C              
[10] LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8
[12] LC_IDENTIFICATION=C       

attached base packages:
 [1] splines   stats4    parallel  stats    
 [5] graphics  grDevices utils     datasets 
 [9] methods   base     

other attached packages:
[1] monocle_2.2.0       DDRTree_0.1.4      
[3] irlba_2.1.2         VGAM_1.0-3         
[5] ggplot2_2.2.1       Biobase_2.34.0     
[7] BiocGenerics_0.20.0 Matrix_1.2-7.1     

loaded via a namespace (and not attached):
 [1] igraph_1.0.1          
 [2] Rcpp_0.12.9           
 [3] cluster_2.0.5         
 [4] magrittr_1.5          
 [5] munsell_0.4.3         
 [6] colorspace_1.3-2      
 [7] lattice_0.20-34       
 [8] R6_2.2.0              
 [9] stringr_1.1.0         
[10] dplyr_0.5.0           
[11] plyr_1.8.4            
[12] tools_3.3.2           
[13] grid_3.3.2            
[14] gtable_0.2.0          
[15] DBI_0.5-1             
[16] matrixStats_0.51.0    
[17] lazyeval_0.2.0        
[18] assertthat_0.1        
[19] tibble_1.2            
[20] reshape2_1.4.2        
[21] RColorBrewer_1.1-2    
[22] HSMMSingleCell_0.108.0
[23] slam_0.1-40           
[24] qlcMatrix_0.9.5       
[25] pheatmap_1.0.8        
[26] stringi_1.1.2         
[27] limma_3.30.9          
[28] fastICA_1.2-0         
[29] scales_0.4.1          
[30] combinat_0.0-8      
```

**Comment by ctrapnell** [comment]
Hi Dakota,

Thanks for the bug report. Just to clarify: does this happen for you outside of Rstudio, or with earlier versions of the IDE? We have seen bugs like this in the past triggered by the IDEs workspace inspector pane, but upgrading igraph to the latest version (which I see you already have) resolved them.  If this doesn’t happen outside of Rstudio, my sense is that this would be better reported to the Rstudio team. 

Cole Trapnell

Assistant Professor

Department of Genome Sciences

University of Washington

http://cole-trapnell-lab.github.io/

On Thu, Feb 02, 2017 at 8:27 AM Dakota Hawkins

<
mailto:Dakota Hawkins <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

I am currently trying to use Monocle for some new scRNAseq analysis. After executing newCellDataSet() RStudio aborts the current session. I am currently working with a relatively small dataset of filtered genes (24 genes by 48 samples), so file size is unlikely an issue. Creating a CellDataSet via command line R works fine, however, saving the object as an .rda file and loading the object in R once again forces a crash. I've replicated this error both on my Linux Mint desktop and my Macbook.

I'm also able to replicate the crashing using a small, fake dataset:

library(monocle) expr_test <- data.frame(S1 = c(1,1), S2 = c(0,0), row.names = c("G1", "G2")) p_data <- data.frame(Group = c(1, 2), row.names = colnames(expr_test)) f_data <- data.frame(Anno = c("Foo", "Bar"), row.names = row.names(expr_test)) cell_data <- newCellDataSet(as.matrix(expr_test), phenoData = new("AnnotatedDataFrame", data = p_data), featureData = new("AnnotatedDataFrame", data = f_data))

Here is my session info with Monocle as the only specific library call:

R version 3.3.2 (2016-10-31) Platform: x86_64-pc-linux-gnu (64-bit) Running under: Ubuntu 16.04 LTS locale: [1] LC_CTYPE=en_US.UTF-8 [2] LC_NUMERIC=C [3] LC_TIME=en_US.UTF-8 [4] LC_COLLATE=en_US.UTF-8 [5] LC_MONETARY=en_US.UTF-8 [6] LC_MESSAGES=en_US.UTF-8 [7] LC_PAPER=en_US.UTF-8 [8] LC_NAME=C [9] LC_ADDRESS=C [10] LC_TELEPHONE=C [11] LC_MEASUREMENT=en_US.UTF-8 [12] LC_IDENTIFICATION=C attached base packages: [1] splines stats4 parallel stats [5] graphics grDevices utils datasets [9] methods base other attached packages: [1] monocle_2.2.0 DDRTree_0.1.4 [3] irlba_2.1.2 VGAM_1.0-3 [5] ggplot2_2.2.1 Biobase_2.34.0 [7] BiocGenerics_0.20.0 Matrix_1.2-7.1 loaded via a namespace (and not attached): [1] igraph_1.0.1 [2] Rcpp_0.12.9 [3] cluster_2.0.5 [4] magrittr_1.5 [5] munsell_0.4.3 [6] colorspace_1.3-2 [7] lattice_0.20-34 [8] R6_2.2.0 [9] stringr_1.1.0 [10] dplyr_0.5.0 [11] plyr_1.8.4 [12] tools_3.3.2 [13] grid_3.3.2 [14] gtable_0.2.0 [15] DBI_0.5-1 [16] matrixStats_0.51.0 [17] lazyeval_0.2.0 [18] assertthat_0.1 [19] tibble_1.2 [20] reshape2_1.4.2 [21] RColorBrewer_1.1-2 [22] HSMMSingleCell_0.108.0 [23] slam_0.1-40 [24] qlcMatrix_0.9.5 [25] pheatmap_1.0.8 [26] stringi_1.1.2 [27] limma_3.30.9 [28] fastICA_1.2-0 [29] scales_0.4.1 [30] combinat_0.0-8

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/cole-trapnell-lab/monocle-release/issues/17
, or

**Comment by swbioinf** [comment]
Just to add I have seen this issue running a small dataset within Rstudio also. 
a) It seems to be due to the small size (~300 features, ~60 cells) of the dataset (if I add 2000x fake features, it runs ok). 
b) Running outside of Rstudio it is fine.

**Comment by Xiaojieqiu** [comment]
Please notice that this issue was mentioned before in this closed issue: 
https://github.com/cole-trapnell-lab/monocle-release/issues/3
Normally we found if we upgrade our igraph to the newest development branch, it resolves the issue. 

You can install the newest develop branch of igraph here: 
https://github.com/igraph/rigraph

**Comment by Xiaojieqiu** [comment]
I think our answers should have provided enough information to resolve this issue. I will close this issue now.
