### ISSUE TITLE
duplicates in reduceDimension with tSNE

### ISSUE THREAD

**Issue by kaji331** [cole-trapnell-lab/monocle-release#174]
Sometimes reduceDimension with tSNE throws me an error "duplicate", even I find there is no duplicates in vstExprs(data). I think reduceDimension transforms the vstExprs(data) and forget an "unique" step before sending data to tSNE algorithm.

**Comment by Xiaojieqiu** [comment]
@kaji331 thanks for pointing out this. Applying `unique` on the data will remove the duplicates and finish tSNE smoothly for you but it is certainly not ideal because the output of tSNE will give a different dimension comparing to the cds and a lot of downstream analysis functions will break up. 

Which version of Monocle are you using? it seems like that you are still using an old version of Monocle with `norm_method` set to be `vst` as default. Please noted that we recently released an alpha version of monocle 3 (http://cole-trapnell-lab.github.io/monocle-release/monocle3/). default method for  `norm_method` set to be `log` in this version. If the duplicates are simply generated during variance stabilization transformation (vst) procedure and your data doesn't have any duplicates, it should fix the issue for you. We also recommend to try `UMAP` instead of `tSNE` as a dimension reduction method for clustering identification (see the mouse cell atlas (MCA) tutorial: http://cole-trapnell-lab.github.io/monocle-release/monocle3/#tutorial-2-mca-dataset-analysis-clustering).

**Comment by kaji331** [comment]
yes, I am using monocle 2 from bioconductor. I think monocle 3 is still alpha, it may be change the workflow in the future. I tried the mouse cell atlas by monocle 2 for estimate dispersion in a 1TB memory cluster. However, it threw me an error: Error in asMethod(object): not support long vector now: memory.c: 3486

**Comment by Xiaojieqiu** [comment]
Hi @kaji331, the `workflow` in monocle 3 is also pretty stable now and it won't change much in the future.  What Monocle 3 will improve in the future includes mainly new approaches to do more generalized differential gene expression tests in complicate data manifold. For the mouse atlas dataset, please check the MCA tutorial ( http://cole-trapnell-lab.github.io/monocle-release/monocle3/#tutorial-2-mca-dataset-analysis-clustering) we released recently. We used delayedArray in monocle 3 to perform block calculations in estimateDispersions and other functions. It doesn't require a lot of memory and works very fast and finishes MCA analysis all the way until clustering in about 30 minutes.

**Comment by kaji331** [comment]
Thank you very much for your help!
