### ISSUE TITLE
Extract genes for each single state

### ISSUE THREAD

**Issue by macsalvin** [cole-trapnell-lab/monocle-release#191]
Hi Monocle Team,
I would like to get all genes from each state of the plot : plot_cell_trajectory(HSMM).
Is it possible?

Thanks a lot in advance.

**Comment by andysheh** [comment]
Hey macsalvin I just tried this out, and it worked for me

# Where cds is the CellDataSet

state_1_cells <- subset(pData(cds), pData(cds)$State == 1)
state_1_cell_names <- rownames(state_1_cells)
state_1_exprs <- subset(exprs(cds), colnames(exprs(cds)) %in% state_1_cell_names)
state_1_genes <- rownames(state_1_exprs)

if you wanted to get the genes for state 2 instead of 1, change the 1 in the first line to 2. Let me know how it worked for you or if you have any other questions.

**Comment by macsalvin** [comment]
Hey @andysheh thank you very much. It works very well also for me!

**Comment by andysheh** [comment]
No problem!
