### ISSUE TITLE
Is there a way to map the original cell ids (sample names) to Monocle's minimum spanning tree?

### ISSUE THREAD

**Issue by mrJeppard** [cole-trapnell-lab/monocle-release#192]
Currently the cell names get munged when the minimum spanning tree (MST) is formed. My original data has cell ids ['cell_1', 'cell_2', 'cell_3' ... ] but the minimum spanning tree has names such as ['Y_1', 'Y_2', "Y_3", ...].

I'd like to know which cell_\* ids of my data correspond to which Y_\* node names of monocle's MST.

Here's how to recreate what I'm experiencing:
```R
library(monocle)

random_cell_ids <- function(n = 5000) {
  a <- do.call(paste0, replicate(5, sample(LETTERS, n, TRUE), FALSE))
  paste0(a, sprintf("%04d", sample(9999, n, TRUE)), sample(LETTERS, n, TRUE))
}
# Make random data
rd <- replicate(110, rnbinom(500, c(3, 10, 45, 100), .1))
colnames(rd)<- random_cell_ids(n = 110)
cds <- newCellDataSet(rd)

cds <- estimateSizeFactors(cds)
cds <- estimateDispersions(cds)
ordering_genes <- subset(dispersionTable(cds), mean_expression>=0.1)
cds <- setOrderingFilter(cds, ordering_genes)
cds <- reduceDimension(cds, max_components = 2, method = "DDRTree")
cds <- orderCells(cds)

mst_names <- igraph::vertex_attr(minSpanningTree(cds))[['name']]
cell_names  <- sampleNames(cds@phenoData)

# The two have zero names in common.
length(intersect(cell_names, mst_names)) == 0 # True 
```

**Comment by Xiaojieqiu** [comment]
Hi @mrJeppard Very good question. Actually, in Monocle 2 or Monocle 3 each cell doesn't necessarily map to one node on the principal graph (Note that although we still use MST, it could actually be a loop or separate trajectory in Monocle 3). This is because in order to facilitate the principal graph learning we use by default a set of centroids to represent the data structure.  And in the end, each cell is projected to the principal graph for pseudotime and branch assignment. 

Basically, if you don't pass `ncenter = NULL` to `reduceDimension` function in Monocle 2, Monocle 2 will use the `cal_ncenter` function to calculate the number of centroids based on the number of cells in your data. Then the reversed graph embedding (DDRTree by default in Monocle 2) will try to find a tree structure that passes through the middle of the data and also optimizes for structure that describes the data topology the best. Monocle 2 then uses `project2MST` function to project each cell to the principal graph node during the pseudotime calculation step. The mathematical details for those operation are described in the method section of the Monocle 2 paper. 

On the other hand, if you do use `ncenter = NULL`, Monocle 2 will treat each cell as a centroid and there will be a one-2-one mapping between each cell to each principal graph node.  But obviously, Monocle 2 will be slow for large dataset withou running with the `centroid` mode. 

Anyway, although there is no one-to-one mapping in most case, you can still map each cell to the principal graph node by finding the principal graph node with the minimal distance to each cell. This mapping has already calculated and stored in this slot: 
`cds@auxOrderingData[["DDRTree"]]$pr_graph_cell_proj_closest_vertex`

Let me know if this helps.

**Comment by mrJeppard** [comment]
Ah, thank you, that definitely helps. So if I wanted a one-to-many mapping of MST node names to cell ids, something like this would work?  
```R
# Cell id to closest MST node.
id_to_mst_node <- cds@auxOrderingData[["DDRTree"]]$pr_graph_cell_proj_closest_vertex

# Change the MST node to match 'name' attribute in igraph ("Y_*").
id_to_mst_node[,1] <- sapply(id_to_mst_node[,1], function(x){paste(c("Y_", x), collapse = "")})

# Make a MST node to cell ids mapping.
mst_node_to_ids <- list()
for (node_name in unique(id_to_mst_node[,1])) {
  mst_node_to_ids[[node_name]] <- names(id_to_mst_node[,1][id_to_mst_node[,1] == node_name])
}
```

**Comment by Xiaojieqiu** [comment]
Yes, @mrJeppard that will work. However, I would like to make a few more clarifications in case you (or others) will use this mapping as a basis for some benchmark of DDRTree. 
Firstly, I would like to add that DDRTree algorithm itself actually returns a matrix `R`.  This matrix provides the result of the **soft k-mean clustering** as we mentioned in the method section of the RGE paper. In this matrix, each row corresponds to a cell's probability assignment to each centroid on the column. That is each cell can be assigned to multiple principal points (As you may understand, cells at branch points are more likely to be assigned to multiple principal points). So this matrix should be regarded as the best mapping between cells to principal points and principal points to cells. The `R` matrix is stored here `@auxOrderingData$DDRTree$R`. (this requires you to use the newest DDRTree version )

For some historical reasons and simplicity of calculation, however, we used the projection procedure I mentioned above to map cells to principal point and then do the pseudo time assignment, etc in monocle.
