### ISSUE TITLE
Correct (best) way to name the cds$Pseudotime and cds$State vectors with cell ids?

### ISSUE THREAD

**Issue by mrJeppard** [cole-trapnell-lab/monocle-release#193]
By default the cds$Pseudotime and cds$State are not labeled with cell ids. Can I use the row names of `cds@auxOrderingData[["DDRTree"]]$pr_graph_cell_proj_closest_vertex` for this purpose? Is there something less roundabout? 

monocle2
```R
library(monocle)

make_data <- function(){
  set.seed(13)
  rd <- replicate(110, rnbinom(500, c(3, 10, 45, 100), .1))
  colnames(rd)<- 1:110
  return(rd)
}

monocle_analysis <- function(expression_matrix){
  # Return a cell data set with monocle analysis completed.
  cds <- newCellDataSet(expression_matrix)
  cds <- estimateSizeFactors(cds)
  cds <- estimateDispersions(cds)
  ordering_genes <- subset(dispersionTable(cds), mean_expression>=0.1)
  cds <- setOrderingFilter(cds, ordering_genes)
  cds <- reduceDimension(cds, max_components = 2, method = "DDRTree")
  cds <- orderCells(cds)
  return(cds)
}

cds <- monocle_analysis(make_data())
pseudotime <- cds$Pseudotime
state_assignment <- cds$State
cell_ids <- row.names(monocle_obj@auxOrderingData[["DDRTree"]]$pr_graph_cell_proj_closest_vertex)
# Name the $State and $Pseudotime vectors with cell ids.
names(pseudotime)<- cell_ids
names(state_assignment) <- cell_ids
```

**Comment by Xiaojieqiu** [comment]
when you access `Pseudotime` and `State` using `cds$`, you are taking one column from the pData. the corresponding cells for them are the `row.names(pData(cds))` or simply `colnames(cds)` (because these two need to match with each other). 

btw, you may only need to use a single size factor when you try to simulate a negative binomial distribution for each of the 110 genes. Also, the command `ordering_genes <- subset(dispersionTable(cds), mean_expression>=0.1)` should be `ordering_genes <- row.names(subset(dispersionTable(cds), mean_expression>=0.1))` because`setOrderingFilter` function requires ordering_genes to be a vector.
