### ISSUE TITLE
newCellDataSet with sparseMatrix

### ISSUE THREAD

**Issue by KerriganBlake** [cole-trapnell-lab/monocle-release#23]
I've been having issues getting newCellDataSet to accept a spareMatrix (and have had this issue since the initial release of monocle 2). Below is my code and the error message I get each time I try to run it. 

```r
bc1 <- newCellDataSet(as(as.matrix(expression.data1),"sparseMatrix"), phenoData = pd1, lowerDetectionLimit=1,expressionFamily = negbinomial.size())

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘annotatedDataFrameFrom’ for signature ‘"dgCMatrix"’
```

My R version is 3.3.1 and monocle version 2.2.0.

**Comment by roryk** [comment]
+1 for this, sparse matrices don't seem to work.

**Comment by ctrapnell** [comment]
Hm, they do for us on Monocle 2.3.5 (the current HEAD). Can you send us a small reproducible example input?

**Comment by ctrapnell** [comment]
BTW, you shouldn't actually convert your matrix to dense with as.matrix prior to passing it to newCellDataSet. We do that in the vignette, because the expression data is stored as a data frame in HSMMSingleCell (because I am a bozo, and updating HSMMSingleCell in BioC is an enormous pain). But we shouldn't do that in the vignette. You should just pass your expression.data1 (assuming its a dgCMatrix) directly to newCellDataSet().

**Comment by KerriganBlake** [comment]
Here's a simple constructed example. I attached a screenshot of my console as well, just in case that's informative. 

```r
library(monocle)
library(Matrix)
example.mat <- matrix(c(0,0,0,0,0,0,0,1,0,0,0,0),ncol= 3,nrow = 4)
rownames(example.mat) <- c("gene1","gene2","gene3","gene4")
colnames(example.mat) <- c("cell1","cell2","cell3")

bc1 <- newCellDataSet(example.mat, expressionFamily = negbinomial.size())

example.mat.sparse <- as(example.mat, "sparseMatrix")
bc1 <- newCellDataSet(example.mat.sparse, expressionFamily = negbinomial.size())
```

![image](https://cloud.githubusercontent.com/assets/7891963/25112071/b0561804-23a3-11e7-9d35-7a5da4bd91fd.png)

**Comment by ctrapnell** [comment]
OK, I understand the problem. The offending lines are these:
`
  if( is.null( phenoData ) )
    phenoData <- annotatedDataFrameFrom( cellData, byrow=FALSE )
  if( is.null( featureData ) ) 
    featureData <- annotatedDataFrameFrom( cellData, byrow=TRUE )
`
Since you aren't passing both featureData and phenoData, newCellDataSet() is trying to make them automatically from the sparseMatrix, which annotatedDataFrameFrom doesn't know how to do. We will add a check for sparse input and code to handle that case, but in the meantime you should be able to work around this by just supplying AnnotatedDataFrames for both featureData and phenoData yourself. You can create them from any dataframe that has rows named for each row and column (respectively) in your expression matrix.

**Comment by KerriganBlake** [comment]
Excellent, thank you for your prompt reply and solution!
