### ISSUE TITLE
max_components vs num_dim in reduceDimension()

### ISSUE THREAD

**Issue by celinesin** [cole-trapnell-lab/monocle-release#253]
Hello!

I'm a bit unclear as to what the arguments "max_components" and "num_dim" in the reduceDimension() function do, could you please clarify?  Are there some "rules of thumb" to follow when choosing these values?

Thanks very much!

http://cole-trapnell-lab.github.io/monocle-release/docs/#trajectory-step-2-reduce-data-dimensionality
https://github.com/cole-trapnell-lab/monocle-release/issues/49#issuecomment-330345012
https://davetang.org/muse/2017/10/01/getting-started-monocle/

**Comment by mochar** [comment]
max_components is the number of dimensions you want returned.
num_dim is the number of dimension for the PCA preprocessing.

**Comment by celinesin** [comment]
thanks for the clarification!

**Comment by mochar** [comment]
No problem. Just to expand a bit on how I figured it out: I usually look the function up on [rdrr.io](https://rdrr.io/bioc/monocle/man/reduceDimension.html). Here we can see that max_components is "the dimensionality of the reduced space". But num_dim is missing because it's in the list of extra arguments (...). In that case I click on the blue "view source" button on the top. Then I either go through the whole function or just look up the parameter with ctrl-f. In the case of num_dim:

      if("num_dim" %in% names(extra_arguments)){ #when you pass pca_dim to the function, the number of dimension used for tSNE dimension reduction is used
        num_dim <- extra_arguments$num_dim #variance_explained
      }
      else{
        num_dim <- 50
      }

You can see that a default of 50 principal components are used if you don't specify it yourself. The comment here is a bit confusing though, I am guessing it was called pca_dim previously. But this line of code makes it pretty clear I think

    cds@auxClusteringData[["tSNE"]]$pca_components_used <- num_dim

**Comment by tmccra2** [comment]
When would you use more than two dimensions?

**Comment by eoindosullivan** [comment]
if you want to create 3d plot you might want to create 3 max_components, and increasing the number of dims will allow you to consider others PCs that are responsible for less of the overall variance in the data but the components of which might be biologically interesting to you

**Comment by Sophia409** [comment]
your answer is wonderful @eoindosullivan
