### ISSUE TITLE
kmeans centers not distinct in new DDRTree version

### ISSUE THREAD

**Issue by skannan4** [cole-trapnell-lab/monocle-release#26]
I find that with some (but not all) of my datasets, I receive an error when performing reduceDimension(object, max_components = 2, reduction_method = "DDRTree"):
Error in kmeans(t(Z), K, centers = centers): initial centers are not distinct.
The problem seems to occur in my smaller datasets (though I'm not sure if that is just by happenstance). This problem has started occurring relatively recently (after release of the new DDRTree version), and is not observed when reverting to an older version of DDRTree. Any ideas for how to fix?

**Comment by skannan4** [comment]
Presumably it's due to this line in DDRTree 0.1.5: 
centers = t(Z)[seq(1, ncol(Z), length.out=K),]

**Comment by Xiaojieqiu** [comment]
Hi Kannan, 

How big is your small dataset? If the number of the cells is smaller than 100, it may create the problem. This is because right now Monocle 2 always uses the ncenter argument by default. To avoid this problem, please set `auto_param_selection = F` for your small dataset (or alternatively set `ncenter = num` where `num` is a value smaller than your cell number ). Please refer to the Monocle 2 preprint on the automatic procedure for calculating the number centroids.

**Comment by Xiaojieqiu** [comment]
I expect this issue has been resolved and am closing the issue for now
