### ISSUE TITLE
10x data formatting

### ISSUE THREAD

**Issue by kathirij** [cole-trapnell-lab/monocle-release#27]
hello,
This is a rather basic question. I am trying to upload the matrix (.mtx) file that is an output of the cellrangerRkit. 

"gbm_cds <- newCellDataSet(exprs(gbm),
                     phenoData = new("AnnotatedDataFrame", data=pData(gbm)),
                     featureData = new("AnnotatedDataFrame", data=fData(gbm)),
                     lowerDetectionLimit = 0.5,
                     expressionFamily = negbinomial.size())"

However, the matrix does not have the correct featureData. I get the error:

"none of your featureData columns are named “gene_short_name”. Some functions will not be able to take this function as an input as a result"

Do I need to change a column title [that is currently labeled as "symbol"] to "gene_short_name"? If not, will it create problems when I run some of the downstream analyses? For example when I calculate dispersions or when I classify cell type hierarchy?

Also,featureData of my matrix looks like this:
```
> fData(gbm)
                      id                       symbol
ENSMUSG00000051951 ENSMUSG00000051951           Xkr4
ENSMUSG00000089699 ENSMUSG00000089699         Gm1992
ENSMUSG00000102343 ENSMUSG00000102343        Gm37381
ENSMUSG00000025900 ENSMUSG00000025900            Rp1
```

**Comment by ctrapnell** [comment]
Yes, we recommend changing the “symbol” column to “gene_short_name” in the featureData table.

Cole Trapnell

Assistant Professor

Department of Genome Sciences

University of Washington

http://cole-trapnell-lab.github.io/

On Fri, May 19, 2017 at 1:11 PM kathirij

<
mailto:kathirij <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

hello,

This is a rather basic question. I am trying to upload the matrix (.mtx) file that is an output of the cellrangerRkit.

"gbm_cds <- newCellDataSet(exprs(gbm),

phenoData = new("AnnotatedDataFrame", data=pData(gbm)),

featureData = new("AnnotatedDataFrame", data=fData(gbm)),

lowerDetectionLimit = 0.5,

expressionFamily = negbinomial.size())"

However, the matrix does not have the correct featureData. I get the error:

"none of your featureData columns are named “gene_short_name”. Some functions will not be able to take this function as an input as a result"

Do I need to change a column title [that is currently labeled as "symbol"] to "gene_short_name"? If not, will it create problems when I run some of the downstream analyses?

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/cole-trapnell-lab/monocle-release/issues/27
, or

**Comment by Xiaojieqiu** [comment]
this is the same issue as in #24 . I will close it now. please refer to the other issue. meanwhile, the monocle 2 website will be updated to incorporate those info
