### ISSUE TITLE
What is the parameter of "reverse" in orderCells function?

### ISSUE THREAD

**Issue by Shanabella** [cole-trapnell-lab/monocle-release#31]
Hi, we are doing pseudotime analysis on single-cell RNA-seq data. The ordering looks good based on known marker genes' expression, but the beginning and ending states are flipped. We tried to run the orderCells function with the reverse parameter, but we don't know what parameter should be inputted. We've tried reverse=true, reverse=1, and some other parameters we could think of, but none of them work. Could you please help us on that? Thanks!

**Comment by dpcook** [comment]
Just to clarify, when the parameter is reverse=FALSE, is the ordering backwards? If so, can you describe the ordering when reverse=TRUE?

**Comment by Shanabella** [comment]
The default parameter is reverse=Null. When I enter reverse=TRUE, nothing changes and the ordering is still backward.

**Comment by Xiaojieqiu** [comment]
How many states do you got in your trajectory? If there are a few, you can identify the initial state for the trajectory and set `root_state` to the identified state in orderCells function so that the principal graph from monocle 2 starts from that state. For example: 
```

lung <- load_lung();  
plot_cell_trajectory(lung, color_by = 'Pseudotime'); 
plot_cell_trajectory(lung, color_by = 'Time');  #identify state 2 as the initial state
lung <- orderCells(lung, root_state = 2);
plot_cell_trajectory(lung) + facet_grid(~State);
```
If it is a linear trajectory and Monocle 2 doesn't reverse the trajectory after  setting `reverse=T`, it maybe a bug we introduced after upgrading our strategy of trajectory reconstruction from ICA based to reversed graph embedding based strategy. It will be an easy fix and I will fix this soon. (For now, you could just use something like
 `pData(lung)$Pseudotime <- max(pData(lung)$Pseudotime) - pData(lung)$Pseudotime` 
to reverse the linear trajectory)

**Comment by byoung** [comment]
Was this issue fixed? I'm passing in reverse=TRUE into the current version of Monocle and it's not flipping the graph around.

**Comment by JihedC** [comment]
> Was this issue fixed? I'm passing in reverse=TRUE into the current version of Monocle and it's not flipping the graph around.

I am also interested in knowing this

**Comment by yxiao832** [comment]
> Was this issue fixed? I'm passing in reverse=TRUE into the current version of Monocle and it's not flipping the graph around.


> > Was this issue fixed? I'm passing in reverse=TRUE into the current version of Monocle and it's not flipping the graph around.
> 
> I am also interested in knowing this

Me too!

**Comment by Shawn10312** [comment]
hi,
in`cds <- setOrderingFilter(cds, ordering_genes)`,
how many 'ordering_genes' used will be rational?
