### ISSUE TITLE
Conda Environment

### ISSUE THREAD

**Issue by MediciPrime** [cole-trapnell-lab/monocle-release#321]
Not really an issue but a request.  

Could someone on your team please create a conda environment for Monocle 3?  

I have spent an entire day trying to install Monocle 3 on my University's cluster but haven't been able to because of various dependencies and no root privileges.  I really want to use Monocle 3 but have no way of doing so without Conda.  

Thank you in advance!

**Comment by pcm32** [comment]
At the EBI we hope to have a monocle3 conda installation as soon as the Trapnell Lab gives us a release tag for monocle3 on this repo. @ctrapnell would that be feasible to happen soon? Otherwise bioconda won't allow us to merge if we are pointing to a commit instead of to a release on github (https://bioconda.github.io/guidelines.html#guidelines). Thanks!

**Comment by SiyiWanggou** [comment]
@MediciPrime I also meet this problem.... Is there any other ways to fix this?

**Comment by MediciPrime** [comment]
@SiyiWanggou sadly no.  I am working on manually compiling the various dependencies and setting up my bashrc to recognize those dependencies.  It will take about 5 months for the people over at bioconda to get Monocle 3 to work.  [Related Issue](https://github.com/bioconda/bioconda-recipes/issues/15212)

**Comment by mjsteinbaugh** [comment]
`r-monocle3` is on now on bioconda. See https://github.com/bioconda/bioconda-recipes/issues/15212 for details. @MediciPrime here's how to add new recipes: https://bioconda.github.io/contributor/index.html
