### ISSUE TITLE
FAIL differentialGeneTest

### ISSUE THREAD

**Issue by yang-william** [cole-trapnell-lab/monocle-release#34]
why do differentialGeneTest fail on a lot of the genes?

![image](https://user-images.githubusercontent.com/23245419/27752817-ea4a5bbe-5db0-11e7-803e-7e4aea4cb660.png)

**Comment by Xiaojieqiu** [comment]
Fail in Monocle means that it cannot fit a model to the data and the likelihood-ratio test is not performed or failed. This either happens when the gene under test expresses only in very few cells or the data distribution doesn't match up the assumed distribution (tobit here) and thus VGLM (the engine/package we used to fit a model) fails to fit the data. 

In the Census paper, I talked about that the tobit model is less robust/accurate comparing to the negative binomial distribution so if your data is already UMI counts or includes spike-in transcript, you should just use counts and negative binomial distribution for DEG test.If you really don't have those data available or you only have relative abundance (like FPKM, TPM), you can consider trying to use Census to convert the relative abundance to relative transcript count and then use  negative binomial distribution for DEG test.

**Comment by yang-william** [comment]
Also another question, what is the default reduction method for the function reduceDimension if none are provided? Thanks.

**Comment by Xiaojieqiu** [comment]
We use DDRTree as default (it is stated in the documentation for reduceDimension). Since your issue was addressed. I will close this issue.
