### ISSUE TITLE
error in plot_genes_branched_pseudotime

### ISSUE THREAD

**Issue by yang-william** [cole-trapnell-lab/monocle-release#43]
On some set of genes, I get the error

Error in full_model_expectation[x[2], x[1]] : subscript out of bounds

What is even weirder is that if I plot those set of genes separately with some random other gene, it works.

Any particular cause for this?

Also, why can't plot_genes_branched_pseudotime work only one 1 gene?

I get the error

"Error in if (nrow(ancestor_exprs) == 1) exprs_data <- t(as.matrix(ancestor_exprs)) else exprs_data <- ancestor_exprs :
  argument is of length zero

when I input data[c(31421),] or data[,31421,] for instance. Thanks.

**Comment by Xiaojieqiu** [comment]
Hi William, I have not run into errors like this. if you can provide minimal data as well as the code to reproduce your error, that will help me to reproduce your error. 

For `plot_genes_branched_pseudotime`, yes, it doesn't support plotting a single cell. I will consider to either add an warning or provide the support for plotting a single gene. 

Thanks

**Comment by yang-william** [comment]
Thank you for the help. Unfortunately, the data set is too large. I think I will just work around this issue b y plotting it against some random other gene.

Also, another question I have is what do the lines represent in plot_genes_branched_pseudotime? Is it the average expression of certain genes along a path? Because I see the line go to places where there are very few cells. Also, I see the line split before it reaches the branch, which doesn't make much sense.

**Comment by Xiaojieqiu** [comment]
you could share with a dropbox link or something if you want. 

Regarding to the line, have you read the documentation / the Census and BEAM paper? 

Here is the information for the documentation: 

**In order to make the bifurcation plot, we first duplicated the progenitor states and by default stretch each branch into maturation level 0-100. Then we fit two nature spline curves for each branchs using VGAM package.**

The bifurcation point for each gene can happen before "reaches the branch" which is actually important point in BEAM branch time point analysis: that is branch time point for each gene can reflect regulatory hierarchy

**Comment by brianpenghe** [comment]
@yang-william I have the same problem

**Comment by brianpenghe** [comment]
If I only plot one gene, using 

> plot_genes_branched_pseudotime(HSMM_major[84,],
+                                branch_point = 1,color_by = "cell_class", ncol = 1)

It will give this error:
Error in if (nrow(ancestor_exprs) == 1) exprs_data <- t(as.matrix(ancestor_exprs)) else exprs_data <- ancestor_exprs : 
  argument is of length zero
