### ISSUE TITLE
Remove Cell cycle affect

### ISSUE THREAD

**Issue by rmtsoa** [cole-trapnell-lab/monocle-release#46]
Hi:

Thanks for putting this tool together. I have a general question about removing the cell cycle affect from the data analysis. Do you have any suggestion to either use regression model to reduce the weight of cell cycle related affect for clustering?

Thanks,
Rosemarie

**Comment by dpcook** [comment]
This reply is a little late, but I figured I'd throw a few comments out for this question. Depending on the biological system you're studying, it can often be justifiable to remove cell cycle effects prior to clustering (otherwise, your clusters may just be cell cycle stage). I've done this two ways 1) model the effect of it and regress it out (Seurat has functions for classification and regressing the effect out; limma's removeBatchEffect could work too I think), or 2) Don't manipulate the expression values at all, but reduce dimensionality and cluster on a gene set that does not contain the common cell cycle genes. I can see a situation these non-cell cycle genes may still be affected by cell cycle state, but if you have enough prior knowledge about your system, you can see if it works (I've had luck with it).

Just remember that if you regress out cell cycle, it's okay to use the resulting expression matrix for clustering, but you would want to use the original matrix for differential expression (including CellCycle as a covariate in both the full and reduced model). Otherwise you'll get a large inflation of false positives.

**Comment by Xiaojieqiu** [comment]
thanks again, @dpcook. I would like to add two more notes:  firstly, the cell cycle effect is normally not an issue for datasets involves cell differentiation and disease progression. As a few papers demonstrated, the variance explained by cell cycle is normally on the scale of 10% or less. In my hands, I never need to use any specific approaches to remove cell cycle effect before running clustering or cell trajectory reconstruction. 
Secondly, as pointed by @dpcook ,   removeBatchEffect can be used for removing the cell cycle effects. Monocle 2 relies on this function and provides the `residualModelFormulaStr` for you to do just that
