### ISSUE TITLE
Is there a connection between the clusters monocle finds and the pseudotime analysis?

### ISSUE THREAD

**Issue by CodeInTheSkies** [cole-trapnell-lab/monocle-release#65]
Just a general question for better understanding.  The online monocle tutorial first describes and gives examples of how to cluster using monocle.  And then we go to the part of pseudotime analysis.  So, my question is, these are separate capabilities of monocle, that have their own uses, correct?  In other words, do we have to first always cluster before doing pseudotime?  Does monocle use the cluster information at all while doing pseudotime analysis?  My understanding is NO, but I thought it will be great to clarify.

Thanks!

**Comment by dpcook** [comment]
Hi CodeInTheSkies,

Yup, you are correct that they are distinct functionalities of monocle. You do not have to cluster prior to pseudotime, and monocle doesn't use cluster ID in the construction of a pseudotemporal trajectory. All the DDRTree (pseudotime) algorithm needs is the expression matrix and a gene list to use for dimensionality reduction.

Just for extra information in case you're not very familiar with it yet, the two methods are similar in that they group cells based on similarities, broadly speaking, but are designed to deal with two different scenarios. When your data has distinct populations (eg. a tissue with multiple cell types), we'll cluster the cells into discrete groups and then we can do things like differential expression between these discrete groups. However, when dealing with a dynamic cell process (eg. differentiation, drug treatment, etc), you don't get discernible groups of cells, but rather you get a smear, where the path of the smear represents the continuous changes associated with the cell process. Clustering cells in this context is really just breaking this smear into arbitrary peaces, often providing no valuable information. Pseudotime involves ordering cells along a trajectory through this smear, providing a continuous variable (pseudotime values) to use for expression modelling instead of a discrete variable like cluster ID.

Hope this helps!

**Comment by CodeInTheSkies** [comment]
Thanks!  That explanation really helps!
