### ISSUE TITLE
Understanding plot_genes_branched_heatmap 

### ISSUE THREAD

**Issue by CodeInTheSkies** [cole-trapnell-lab/monocle-release#74]
Hello!

Sorry for asking so many questions, but it's just that the package is great, and I can't stop exploring it to its full potential!

I would like to understand what the function "plot_genes_branched_heatmap" does more clearly.  I have gone through all available explanations in the monocle tutorial page, but what I don't get clearly is what exactly do the columns in the branched heatmap represent?  Are they "cells"?  The tutorial says the column is pseudotime, but then they have to represent cells in some way since each gene-expression value would correspond to a cell, no?  Or, is it that the entire x-axis is an interpolation?  I see that the two branches, left lineage and right lineage are always symmetrical, even if the actual proportions of cells in different states in the two lineages aren't.  Maybe I'm confusing too much, but a clear explanation of what exactly the columns of the branched heatmap represent would be wonderful!

Thanks a lot!

**Comment by dpcook** [comment]
Hey Code,
If you're looking for a deeper understanding of what the function is doing, I'd recommend digging into the source code for the function. The plot_genes_branched_heatmap function is in R/plotting.R, but it calls a nested function (buildBranchCellDataSet) that's contained in R/BEAM.R. I found it valuable to run through the code line by line and see what variables get made/changed.

But to briefly answer your question, monocle orders your cells along the trajectory, giving each cell a pseudotime value. Now, with expression values for each gene at different points in pseudotime (ie. each cell), it uses a VGLM with splines to fit non-linear expression dynamics as a function of pseudotime. This model can then directly be used for differential expression if desired (eg. using a likelihood ratio test against a reduced model that doesn't incorporate pseudotime). For plotting a heatmap though, there's a problem: the pseudotime values for your cells do not increase by sequential integers (ie. 1,2,3,..,n). This is because monocle was designed, recognizing that the jump between cells along a trajectory aren't always the same distance. So if you were to make a heatmap, your column representation of pseudotime wouldn't be linear--it will depend on your sampling density along the trajectory. It could go, for example, 1,1.15,1.25,5,6,6.25,10 (see the problem?). So what the plotting function does (more specifically, a function called genSmoothCurves) is use the constructed models from before to predict gene expression of all genes along 100 evenly spaced pseudotime values spanning the range, and then makes a heatmap of those predictions rather than your scRNA-Seq measurements themselves. Each column represents those one of those 100 pseudotime values.

The branched heatmap function is similar, except things are ordered differently. Those modelled values are ordered from the middle of the heatmap outwards. The left and right directions represent the modelled expression for two separate branches of the trajectory. The small region in the middle that is symmetrical represents the "progenitors" (the nomenclature used by the devs) prior to the branchpoint, and the point moving outwards where that symmetry breaks is the bifurcation point of the two independent branches. Going through the source code for this would really help make this clear.

**Comment by CodeInTheSkies** [comment]
Thanks for the nice explanation!

**Comment by Xiaojieqiu** [comment]
thanks @dpcook

**Comment by lincoln-harris** [comment]
This is a great explanation, but how can I tell which branch is which, ie. which branch in my trajectory map corresponds to 'cell fate 1' and which corresponds to 'cell fate 2'? Pseudotime heat maps like this aren't much use if I can't tell which branch my genes of interest are high vs low in...

**Comment by wasqqdyx** [comment]
I do have the same issue with Lincoln. I wonder if there is any way to tell the mapping of trajectory branches with the heatmap branches? Thanks!

**Comment by cemalley** [comment]
Agree with others in this thread, @dpcook or @Xiaojieqiu could you explain how monocle decides which section of the pseudotime branchpoint is taken for cell fate 1 and cell fate 2? We are interested in finding branch-dependent DE genes at each branchpoint. Thank you.

**Comment by AlexLOTR** [comment]
> This is a great explanation, but how can I tell which branch is which, ie. which branch in my trajectory map corresponds to 'cell fate 1' and which corresponds to 'cell fate 2'? Pseudotime heat maps like this aren't much use if I can't tell which branch my genes of interest are high vs low in...

I forget where I saw this, but remember:
Cell fate 1 always represents the smaller No. of 'state', and cell fate 2 represents the larger No. of 'state'.
ie. There are 1 to 5 states in your plot, the branchpoint you are looking into is 'branch 1', which comes from 'state 1' and connects to' state 2' and 'state 4' along the pseudotime. In this case, cell fate 1 represents 'state 2', and cell fate 2 represents 'state 4'.

**Comment by SSSJe** [comment]
> > This is a great explanation, but how can I tell which branch is which, ie. which branch in my trajectory map corresponds to 'cell fate 1' and which corresponds to 'cell fate 2'? Pseudotime heat maps like this aren't much use if I can't tell which branch my genes of interest are high vs low in...
> 
> I forget where I saw this, but remember: Cell fate 1 always represents the smaller No. of 'state', and cell fate 2 represents the larger No. of 'state'. ie. There are 1 to 5 states in your plot, the branchpoint you are looking into is 'branch 1', which comes from 'state 1' and connects to' state 2' and 'state 4' along the pseudotime. In this case, cell fate 1 represents 'state 2', and cell fate 2 represents 'state 4'.

Maybe fault. 

<img width="932" height="433" alt="Image" src="https://github.com/user-attachments/assets/83662ed8-0733-47b1-890e-eb6293a33c64" />
