### ISSUE TITLE
Installation in 3.3.2

### ISSUE THREAD

**Issue by yonchoi** [cole-trapnell-lab/monocle-release#75]
Hi, 

I am trying to install the package in 3.3.3, but is giving me error saying that one of the dependencies VGAM is not available only available for 3.4.0 or new version. However, the monocle requirement is 3.0 or above. Did you have any issues regarding this?

Thank you!

**Comment by Xiaojieqiu** [comment]
Since VGAM package relies on R3.4.0. Please consider update your R.
You may need something like the following to install Monocle's dependent packages before installing Monocle . 

#install all packages: 
packages = c("ggplot2", "VGAM", "igraph", "pRlyr", "combinat", "fastICA", "irlba", "matrixStats", "reshape2", "R.utils", "snow", "tsne", "lle", "DDRTree", "rEDM"
          "tidyr",  "dplyr", "stringr", "modeest", "Hmisc", "boot", "doMC", "data.table", "fitdistrplus", "ggdendro", "gplots", "princurve", "sp", "devtools", "gridExtra",
        "lmtest", "MASS", "mixsmsn", "pheatmap", "plyr", "pscl", "RColorBrewer", "VennDiagram", "zoo", "raster", "colorRamps", "grid", "ROCR", 
        'scatterplot3d', 'TTR', 'ComplexHeatmap', 'circlize', 'Rtsne', 'FNN', 'reshape', 'qlcMatrix', 'proxy', 'slam', 'R.matlab', 'flexclust', 'mcclust',
        'roxygen2', 'testthat')

install.packages(packages, repo = 'http://cran.fhcrc.org/') 

################################################################################################################################################
#install bioconductor packages
################################################################################################################################################
bio_packages = c("Biobase", "BiocGenerics",  "limma", "ComplexHeatmap", "HSMMSingleCell", 'GEOquery', 'DESeq', 'DESeq2', 'piano', 'edgeR',  'MAST', 'destiny', 'monocle')
source("http://bioconductor.org/biocLite.R")
biocLite(bio_packages)
