### ISSUE TITLE
example files for tutorial section 2.1

### ISSUE THREAD

**Issue by croth1** [cole-trapnell-lab/monocle-release#8]
I am trying to run your tutorial. In section 2.1 you are using three text file:

fpkm_matrix.txt
cell_sample_sheet.txt
gene_annotations.txt

Did you upload the example files you used somewhere? I couldn't find them on github.

Thanks!

**Comment by ctrapnell** [comment]
These files aren’t included in the GitHub repo, as they are kind of large.  We host the data through Bioconductor in the HSMMSingleCell package. They are stored there as rda files, not text files.

Cole Trapnell

Assistant Professor

Department of Genome Sciences

University of Washington

http://cole-trapnell-lab.github.io/

On Fri, Oct 21, 2016 at 6:56 AM Christian Roth

<
mailto:Christian Roth <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

I am trying to run your tutorial. In section 2.1 you are using three text file:

fpkm_matrix.txt

cell_sample_sheet.txt

gene_annotations.txt

Are there example files available? I couldn't find them on github.

Thanks!

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/cole-trapnell-lab/monocle-release/issues/8
, or
