### ISSUE TITLE
BEAM use a different differentially expressed gene analysis function?

### ISSUE THREAD

**Issue by bitttyyyy** [cole-trapnell-lab/monocle-release#81]
Hi there, 

I tried to use BEAM to do branch analysis and the result looked great. However, there are many known markers for specific branch development was considered as failed. Possible reason is that those markers are only expressed highly in a small population of cells and do not fit the model for the differentially expressed gene analysis used in BEAM. Therefore, I was wondering if there is a way to use negative binomial distribution for calculating q-val in BEAM?

Thank you so much!

**Comment by Xiaojieqiu** [comment]
The BEAM test in Monocle 2 also uses the same generalized linear models framework as the differentialGeneTest function, and also assumes the data follow negative binomial distribution. But it is a much more restricted test since it tries to fit two separate curves over pseudotime for each branch. If your data is sparse with only a few number of cells expressing a marker, Monocle 2 will fail to fit curves for it. 
If you still want to test for genes different across two branch, I suggest you to simply do a differentialGeneTest across two branches by setting `fullModelFormulaStr = "~branch"` in the `differentialGeneTest`. This approach will identify genes differ across branches but ignores the dynamic divergence across two branches.
