### ISSUE TITLE
could not find function "disp_func" during the running of plot_genes_branched_heatmap

### ISSUE THREAD

**Issue by SmileZero** [cole-trapnell-lab/monocle-release#94]
I got some errors as below when I was running ```plot_genes_branched_heatmap```. It is for analyzing a single cell trajectory, and I have no clue how to fix it:
```
<simpleError in checkwz(wz, M = M, trace = trace, wzepsilon = control$wzepsilon): NAs found in the working weights variable 'wz'>
Error in disp_func(expr_hint) : could not find function "disp_func"
```

I followed the steps in the official tutorial. The errors only appeared at some branch point I indicated. I will be appreciated if anyone can give me some hints.

**Comment by dwucsf** [comment]
Hey SmileZero, how did you solve this error? I'm getting the same one in Monocle 3

**Comment by JihedC** [comment]
I am also interested in knowing this

**Comment by SmileZero** [comment]
Sorry, I just saw the comments here. I don't remember clearly how I fixed it but one thing important is that you need to choose your `expressionFamily` in monocle 2.

**Comment by EAC-T** [comment]
Anyone can help on this issue?

**Comment by yekong-ouc** [comment]
Hi, I've figured out where the problem lies. It turns out that the genes calculated are incorrect. Specifically, there's an issue with one of the genes in cds[genes,]. You can successfully run the code by making adjustments, but I'm not sure what the exact problem is.嗨，我发现了问题出在哪里，是算出来的基因不对，是cds[genes,]中genes里的某个基因跑不出来，你可以通过调整来成功实现代码，但具体是什么问题我不知道
